### ISSUE TITLE
unexpected keyword auto_install

### ISSUE THREAD

**Issue by MasIgor** [BlueMirrors/Yolov5-TensorRT#14]
Hello!

thank you for your hard work. I am trying to run it with my onnx file and it is not working:

```
PS E:\Workfolder\yolov5\Yolov5-TensorRT> python detect.py --input 'test.jpg' --output 'out.jpg' --weights bests.onnx
Traceback (most recent call last):
  File "detect.py", line 126, in <module>
    not opt.no_auto_install)
  File "detect.py", line 68, in detect_image
    auto_install=auto_install)
TypeError: __init__() got an unexpected keyword argument 'auto_install'
```

I installed CVU with 'pip install cvu-python' because with install requirements it failed:

```
PS E:\Workfolder\yolov5\Yolov5-TensorRT> pip install -r requirements.txt
Collecting git+https://github.com/BlueMirrors/cvu (from -r requirements.txt (line 1))
  Cloning https://github.com/BlueMirrors/cvu to c:\users\igor~1.mas\appdata\local\temp\pip-req-build-i6rnrlj0
  Running command git clone -q https://github.com/BlueMirrors/cvu 'C:\Users\IGOR~1.MAS\AppData\Local\Temp\pip-req-build-i6rnrlj0'
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\igor.masin\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\IGOR~1.MAS\\AppData\\Local\\Temp\\pip-req-build-i6rnrlj0\\setup.py'"'"'; __file__='"'"'C:\\Users\\IGOR~1.MAS\\AppData\\Local\\Temp\\pip-req-build-i6rnrlj0\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\IGOR~1.MAS\AppData\Local\Temp\pip-pip-egg-info-2yxg3pjx'
         cwd: C:\Users\IGOR~1.MAS\AppData\Local\Temp\pip-req-build-i6rnrlj0\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\IGOR~1.MAS\AppData\Local\Temp\pip-req-build-i6rnrlj0\setup.py", line 10, in <module>
        README = (HERE / "README.md").read_text()
      File "c:\users\igor.masin\appdata\local\programs\python\python37\lib\pathlib.py", line 1222, in read_text
        return f.read()
      File "c:\users\igor.masin\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1278: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
W
```

any help appreciated.. 

Thank you!

**Comment by shivamswarnkar** [comment]
Hi, @tanzerlana, thanks for checking out work.

Actually ```cvu``` published on pip is not up to date with the repo and doesn't have the ```auto_install``` option yet. So I'd recommend uninstalling it for now.

If install from requirements is failing then I would recommend cloning the [cvu repo from here](https://github.com/BlueMirrors/cvu), and placing the ```cvu``` folder from the ```cvu-repo``` in your local ```Yolov5-TensorRT``` folder. Then everything should work out.

We'll check why the requirements install failed on your windows in the meantime.  
Also, we plan to publish the latest ```cvu``` in the upcoming weeks, though that can take some time.
