### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'serialize'

### ISSUE THREAD

**Issue by Jash2402** [BlueMirrors/Yolov5-TensorRT#15]
I'm using this command "python3 convert.py --weights best.onnx --img-size 720 1080" to convert a custom trained ONNX file to tensorRT engine. 
However I come across the error "AttributeError: 'NoneType' object has no attribute 'serialize'" while running the above mentioned command. Could you please advise on how to sort this issue ?

**Comment by makaveli10** [comment]
@Jash2402 Can you please share the below details:
Ubuntu Version: 
TensorRT version/Tag(if using docker):
Error Stacktrace(what you see on the terminal):

Please check if you converted your ONNX model with the shape you are using in ONNX -> TensorRT conversion.

**Comment by shivamswarnkar** [comment]
closing issue due to inactivity. Feel free to reopen if needed

**Comment by rashmi-tiwari** [comment]
Hii, @shivamswarnkar, getting the same issue while converting the model to TensorRT. 
I am using latest Yolov5s weights.
Pycuda version:  2021.1
TensorRT version: 8.4.0.6
Traceback (most recent call last):
  File "convert.py", line 78, in <module>
    convert_onnx_to_trt(opt.weights,
  File "convert.py", line 29, in convert_onnx_to_trt
    convert(np.random.randint(0, 255, image_shape).astype("float"))
  File "/home/rashmi/anaconda3/envs/tensort_RT/lib/python3.8/site-packages/cvu/detector/yolov5/core.py", line 102, in __call__
    outputs = self._model(processed_inputs)
  File "/home/rashmi/anaconda3/envs/tensort_RT/lib/python3.8/site-packages/cvu/detector/yolov5/backends/yolov5_tensorrt.py", line 307, in __call__
    self._load_model(self._weight)
  File "/home/rashmi/anaconda3/envs/tensort_RT/lib/python3.8/site-packages/cvu/detector/yolov5/backends/yolov5_tensorrt.py", line 141, in _load_model
    self._engine = self._build_engine(weight, engine_path,
  File "/home/rashmi/anaconda3/envs/tensort_RT/lib/python3.8/site-packages/cvu/detector/yolov5/backends/yolov5_tensorrt.py", line 262, in _build_engine
    trt_engine_file.write(engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'

Kindly share how to resolve the error. Thank you

**Comment by shivamswarnkar** [comment]
Hi @rashmi-tiwari, it seems to be an issue with the latest weights. We have identified the cause and we're working on fixing it.  I'll notify you once we have released the fix. 

You can also read about it here https://github.com/BlueMirrors/cvu/issues/27
