### ISSUE TITLE
got unexpected argument 'fp16' in converting

### ISSUE THREAD

**Issue by Daryatnt** [BlueMirrors/Yolov5-TensorRT#18]
Hi 

how do i solve this problem?
```
best7.onnx
[CVU-Info] Backend: Tensorrt-8.4.0.6-cuda
Exception ignored in: <function Yolov5.__del__ at 0x7f779bcf8830>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/cvu/detector/yolov5/backends/yolov5_tensorrt.py", line 384, in __del__
    self._ctx.pop()
AttributeError: 'Yolov5' object has no attribute '_ctx'
Traceback (most recent call last):
  File "convert.py", line 75, in <module>
    auto_install=not opt.no_auto_install)
  File "convert.py", line 23, in convert_onnx_to_trt
    ,fp16=True)
  File "/usr/local/lib/python3.7/dist-packages/cvu/detector/yolov5/core.py", line 78, in __init__
    self._load_model(backend, weight, device, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/cvu/detector/yolov5/core.py", line 173, in _load_model
    **kwargs)
TypeError: __init__() got an unexpected keyword argument 'fp16'
```

**Comment by shivamswarnkar** [comment]
Hi @Daryatnt , did you install ```cvu-python``` directly with pip or through ```requirement.txt```?

**Comment by NaveedAI** [comment]
Hi, 
I have the same issue and I did install `cvu-python` directly through `requirements.txt`. Could you please guide?

**Comment by shivamswarnkar** [comment]
@NaveedAI @Daryatnt #20 should fix this issue. Feel free to re-open this issue if it still persists. Thanks for pointing it out.
